### PR TITLE
Use scratch-gui source instead of its build output

### PR DESCRIPTION
**Pull request by cwillisf**
### Resolves

In support of #97 / #103

### Proposed Changes

Use `scratch-gui` source instead of its build output. 

In support of this:
- added `scripts/rebuild-deps.js` (and hooked it up to `npm run rebuild-deps`) to merge `scratch-gui`'s dependencies with `scratch-desktop`'s dependencies and write the result into `scratch-desktop`'s `package.json` file.
   - `scratch-desktop`'s own dependencies (`devDependencies`) are now stored in a new `package-deps.json` file for the purposes of this merge process
   - all other fields in `package.json`, including the version, are preserved through the merge. This means (for example) `npm version` still works as expected.
- the `webpack.*.js` config files in `scratch-desktop` now export functions instead of objects, which allows them to modify the default config before attempting to merge
   - if these files return objects, as they did before, `electron-webpack` will use `webpack-merge.smart(...)` to merge the configurations. In this scenario the only way to override a default rule is to include a new rule with an exact match in the `test` field, and removing a rule completely is impossible.
   - in this new configuration I've added a new step which removes rules by file extension
   - for more info, see https://webpack.electron.build/modifying-webpack-configurations#using-a-config-function and electron-userland/electron-webpack#254
- copied webpack rules for CSS and image files from `scratch-gui` into `webpack.renderer.js`
- removed `source-map-loader` since it's no longer necessary

### Reason for Changes

This will allow `scratch-desktop` to use `scratch-gui` components without exposing them through `scratch-gui/src/index.js`. I exposed `AppStateHOC` a while ago, but implementing the "About" menu (the upcoming `(?)` button) would be easier if `scratch-desktop` had access to `scratch-gui`'s `MenuItem` and friends. I considered exposing those, too, but rather than exposing various components seemingly at random, I think it would be better to allow scratch-desktop to reach "in" as needed.

In addition, this simplifies and speeds up the build process for `scratch-desktop`, and is another step toward `scratch-desktop` being able to use the `develop` branch of `scratch-gui`.

### CODE REVIEW

**Comment by cwillisf** [comment]
Oops, looks like I got something wrong with the libraries... brb...

**Comment by cwillisf** [comment]
sorry for all the force-push noise... I got the package-lock.json wrong and it took a few rounds to figure out what I did wrong due to confusion between `source-map-loader` (which is no longer needed) and `source-map-support` (which is still relevant)

**Review by rschamp — APPROVED** [review]
This looks good as is, but there are two follow-up items we considered in our in-"person" review session:
1. In the short-term, we can avoid the `package-deps.json` file and the associated scripting to keep `package-deps.json` up to date if we modify `scratch-gui`'s `package.json` so that its webpack dependencies are true `dependencies`, so they install with `scratch-gui`, like `scratch-render` and the other `scratch-*` subdependencies.
2. In the long-term, we should decide how we expect external projects to import `scratch-gui`'s internal components: do we really want them to reach into `src/`, or should we export a bunch of decontextualized components into `dist/`?

**Comment by cwillisf** [comment]
Filed #144 to track the `package-deps.json` concern.

**Pull request merged**
